# Generated by Django 4.1.5 on 2023-02-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='passwd',
            new_name='password',
        ),
    ]
