# Generated by Django 4.1.5 on 2023-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_passwd_user_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name', models.CharField(max_length=100)),
                ('police_birthday', models.CharField(max_length=200)),
                ('police_gender', models.CharField(max_length=500)),
                ('police_email', models.CharField(max_length=500)),
                ('police_password', models.CharField(max_length=500)),
                ('police_phone', models.IntegerField()),
                ('police_department', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
