# Generated by Django 4.1.5 on 2023-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_police_details_user_details_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_address',
        ),
    ]
