# Generated by Django 4.1.5 on 2023-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_details_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_details',
            name='Badge_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
