# Generated by Django 4.1.5 on 2023-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_police_details_badge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_details',
            name='Batch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
