# Generated by Django 4.1.5 on 2023-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_police_details_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_details',
            name='police_photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
