# Generated by Django 4.1.5 on 2023-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_police_details_police_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_details',
            name='station',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
