# Generated by Django 4.1.5 on 2023-03-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_police_details_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='police_details',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station'),
        ),
    ]
