# Generated by Django 4.1.5 on 2023-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_station_alter_police_details_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police_details',
            name='station',
        ),
    ]
