# Generated by Django 4.1.5 on 2023-03-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_police_details_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='station',
        ),
    ]
