# Generated by Django 4.1.5 on 2023-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_news_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='stationn',
            field=models.CharField(max_length=100),
        ),
    ]
