# Generated by Django 4.1.5 on 2023-04-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_complaint_stationn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='userphoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
