# Generated by Django 4.1.5 on 2023-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_details_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminalname', models.CharField(max_length=100)),
                ('criminal_date_of_birth', models.CharField(max_length=200)),
                ('criminal_gender', models.CharField(max_length=500)),
                ('criminal_email', models.CharField(max_length=500)),
                ('criminal_password', models.CharField(max_length=500)),
                ('criminal_phone', models.IntegerField()),
                ('crime', models.CharField(max_length=200)),
                ('criminal_address', models.CharField(max_length=200)),
                ('case_status', models.CharField(max_length=200)),
                ('registered_station', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=200)),
                ('evidence', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='police_details',
            name='police_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
