# Generated by Django 4.1.5 on 2023-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_criminaldetails_alter_police_details_police_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetails',
            name='criminal_date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='criminaldetails',
            name='identity',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
