# Generated by Django 4.1.5 on 2023-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_criminaldetails_criminal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetails',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
