# Generated by Django 4.1.5 on 2023-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_police_details_police_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='stationn',
            field=models.CharField(max_length=100),
        ),
    ]
