# Generated by Django 4.1.5 on 2023-04-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_complaint_stationn_complaint_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='station',
        ),
    ]
