# Generated by Django 4.1.5 on 2023-04-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_complaint_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.station'),
            preserve_default=False,
        ),
    ]
