# Generated by Django 4.1.5 on 2023-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_complaint_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
