# Generated by Django 4.1.5 on 2023-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_complaint_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimage', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
