# Generated by Django 4.1.5 on 2023-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_webcamimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=300)),
                ('User_phone', models.BigIntegerField()),
                ('User_address', models.TextField()),
                ('User_pic', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='xx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_pic', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
