# Generated by Django 4.1.5 on 2023-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='uname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
